import type { Metadata } from 'next';
import { Arimo, Cousine, Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/providers/AuthProvider/AuthProvider';
import { NextIntlClientProvider } from 'next-intl';
import ScrollToTopButton from '@/components/UI/ScrollToTopBtn/ScrollToTopButton';
import TanStackProvider from '@/providers/TanStackProvider/TanStackProvider';
import SocketProvider from '@/providers/SocketProvider/SocketProvider';
import { IS_DEMO } from '@/lib/config/demo';
import DemoBanner from '@/components/DemoBanner/DemoBanner';
import DemoWelcome from '@/components/DemoWelcome/DemoWelcome';

const arimoSans = Arimo({
  variable: '--font-arimo-sans',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const cousineSans = Cousine({
  variable: '--font-cousine-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Sistema di Gestione Manutenzione e Comunicazioni',
  description: 'Generated by create next app',
  // SVG favicon first (scales to any tab/bookmark density); PNG stays as
  // a fallback for browsers without SVG favicon support.
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon.png', type: 'image/png' },
    ],
    apple: '/icon-192.png',
  },
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${arimoSans.variable} ${cousineSans.variable} ${interSans.variable}`}
    >
      <body>
        <NextIntlClientProvider>
          <TanStackProvider>
            <AuthProvider>
              <SocketProvider>
                <Toaster position="bottom-right" />
                {IS_DEMO && <DemoBanner />}
                {modal}
                {children}
                {IS_DEMO && <DemoWelcome />}
                <ScrollToTopButton showAfter={700} />
              </SocketProvider>
            </AuthProvider>
          </TanStackProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
