import type { Metadata } from 'next';
import { Arimo, Cousine, Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const arimoSans = Arimo({
  variable: '--font-arimo-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const cousineSans = Cousine({
  variable: '--font-cousine-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Sistema di Manutenzione e Segnalazioni',
  description: 'Generated by create next app',
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimoSans.variable} ${cousineSans.variable} ${interSans.variable}`}
      >
        <Toaster position="bottom-right" />
        {modal}
        {children}
      </body>
    </html>
  );
}
