import type { Metadata } from 'next';
import { Arimo, Cousine, Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/providers/AuthProvider/AuthProvider';
import { NextIntlClientProvider } from 'next-intl';
import Header from '@/components/Header/Header';

const arimoSans = Arimo({
  variable: '--font-arimo-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const cousineSans = Cousine({
  variable: '--font-cousine-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const interSans = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Sistema di Manutenzione e Segnalazioni',
  description: 'Generated by create next app',
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${arimoSans.variable} ${cousineSans.variable} ${interSans.variable}`}
    >
      <body>
        <NextIntlClientProvider>
          <AuthProvider>
            <Toaster position="bottom-right" />
            <Header />
            {modal}
            {children}
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
